name: tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '7.2.x'
          - '7.3.x'

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Check coding style
      run: composer cs-check

    - name: Static analysis tool
      run: composer psalm

    - name: Run test suite
      run: composer test-coverage

    - name: Upload coverage results
      run: |
        wget https://scrutinizer-ci.com/ocular.phar
        php ocular.phar code-coverage:upload --format=php-clover clover.xml
